- uses: port-labs/port-github-action@v1
  with:
    clientId: "DldbSZ3KAdgaYPWqYOvxDKOYbQgwVeDl"
    clientSecret: "OG5MXN1NboQYsjbDSl363yZUWH2kKQAE7cFKApXCG7fL0VP3ciQEh12uUBfV8WOT"
    operation: UPSERT
    identifier: new-cijob-run
    icon: GithubActions
    blueprint: ciJob
    properties: |
      {
        "commitHash": "${{ env.GITHUB_SHA }}",
        "jobBranch": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/tree/${{ env.GITHUB_REF_NAME }}",
        "runLink": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}",
        "triggeredBy": "${{ env.GITHUB_ACTOR }}"
      }
